[package]
version = "0.1.0"
name = "hello-program"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
verifier.workspace = true
tests.workspace = true
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", branch = "main" }
serde_json = "1.0.117"
